prSections:
  - title: Homebrew
    filters: repo:Homebrew/homebrew-core is:open
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  prApproveComment: ""
keybindings:
  prs:
    - key: a
      command: gh pr review --repo {{.RepoName}} --approve {{.PrNumber}}
repoPaths:
  :owner/:repo: ~/Code/:owner/:repo
  Homebrew/brew: /opt/homebrew
  Homebrew/homebrew-*: /opt/homebrew/Library/Taps/homebrew/homebrew-*
pager:
  diff: delta --paging=always
