[[provider]]
provider = "github"
name = "branchv"
path = "."
env_var = "GITHUB_TOKEN"
auth_http = true
skip_forks = true

[[provider]]
provider = "github"
name = "python-poetry"
path = "."
env_var = "GITHUB_TOKEN"
auth_http = true
skip_forks = true
