"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
aliases = ["config", "list", "aliases"]
amend = ["squash"]
fixup = ["util", "exec", "--", "sh", "-c", "jj squash && jj upload"]
stash = ["new", "@-"]

[ui]
default-command = "log"
diff-formatter = ":git"
pager = ["delta", "--diff-so-fancy", "--navigate"]
