"$schema" = "https://jj-vcs.dev/latest/config-schema.json"

[user]
name = "Branch Vincent"
email = "branchevincent@gmail.com"

[aliases]
aliases = ["config", "list", "aliases"]
amend = ["squash"]
fixup = ["util", "exec", "--", "sh", "-c", "jj squash && jj upload"]
stash = ["new", "@-"]

[ui]
default-command = "log"
diff-formatter = ":git"
pager = ["delta"]
